"""Gateway capability descriptor for client bootstrap."""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from EyeOfTerror.model_brain import model_contract

from .actions import gateway_actions
from .brigade import governor_registry_snapshot, registry_summary, worker_registry_snapshot
from .views import executable_client_action


def gateway_capabilities() -> dict[str, Any]:
    governors = governor_registry_snapshot()
    workers = worker_registry_snapshot()
    actions = gateway_actions()
    next_action = {"kind": "inspect_state", "method": "GET", "endpoint": "GET /state", "body": {}, "reason": "inspect current gateway state"}
    return {
        "ok": True,
        "gateway": "WarmasterGateway",
        "api_version": 1,
        "actions": actions,
        "summary": {
            "governors": registry_summary(governors),
            "workers": registry_summary(workers),
        },
        "model_brain": model_contract("WarmasterGateway", "top-level orchestration gateway", layer="gateway_service"),
        "display": {
            "headline": "Abaddon capabilities",
            "detail": f"{len(governors)} governors, {len(workers)} workers, {len(actions.get('preferred_task_flow', []))} preferred task-flow steps",
            "severity": "info",
        },
        "next_action": next_action,
        "client_action": executable_client_action("", next_action),
        "command_protocol_endpoints": [
            "POST /orchestrate_run",
            "POST /orchestrate",
            "GET /runs/{task_id}/orchestration",
            "GET /runs/{task_id}/activity",
        ],
        "diagnostic_endpoints": [
            "POST /task_preflight",
        ],
        "capabilities": [
            "model_backed_gateway_orchestration",
            "task_routing",
            "multi_governor_route_detection",
            "decomposition_required_preflight",
            "campaign_preflight",
            "campaign_prepare",
            "campaign_state",
            "campaign_start_resume_cancel",
            "campaign_handoff_protocol",
            "campaign_final_review",
            "task_preflight",
            "task_prepare_orchestration",
            "task_submit_orchestration",
            "run_start_orchestration",
            "run_orchestration_state",
            "run_preparation",
            "run_listing",
            "run_status_summary",
            "run_orchestration_cards",
            "run_governor_activity",
            "ledger_read",
            "artifact_listing",
            "artifact_text_read",
            "final_package_read",
            "controlled_skitarii_patch_apply",
            "http_governor_planning",
            "run_contract_read",
            "run_package_diagnostics",
            "run_oversight_read",
            "run_dispatch_read",
            "run_worker_task_read",
            "run_events_read",
            "global_run_events_read",
            "local_execution",
            "http_worker_execution",
            "background_execution",
            "cooperative_cancellation",
            "worker_cancel_fanout",
            "stale_run_recovery",
            "startup_stale_run_recovery",
            "interrupted_run_resume",
            "governor_registry",
            "governor_health_snapshot",
            "worker_registry",
            "worker_health_snapshot",
            "brigade_plan_snapshot",
            "brigade_health_snapshot",
            "brigade_readiness_summary",
            "state_snapshot",
            "process_active_run_snapshot",
            "run_action_hints",
            "run_step_artifact_read",
            "run_execution_preflight",
            "restricted_step_execution",
            "research_revision_loop",
            "recoverable_run_listing",
            "doctor",
        ],
        "endpoints": [
            "GET /health",
            "GET /capabilities",
            "GET /state",
            "GET /state?health=1",
            "GET /recovery",
            "GET /doctor",
            "GET /brigade_plan",
            "GET /brigade_plan?host=127.0.0.1",
            "GET /brigade_health",
            "GET /brigade_health?host=127.0.0.1",
            "GET /governors",
            "GET /governors?health=1",
            "GET /workers",
            "GET /workers?health=1",
            "GET /events",
            "GET /events?limit=20",
            "GET /events?after=0",
            "POST /task_preflight",
            "POST /campaign_preflight",
            "POST /campaign",
            "GET /campaigns",
            "GET /campaigns/{campaign_id}",
            "POST /campaigns/{campaign_id}/start",
            "POST /campaigns/{campaign_id}/resume",
            "POST /campaigns/{campaign_id}/cancel",
            "POST /orchestrate",
            "POST /orchestrate_start",
            "POST /orchestrate_run",
            "GET /runs",
            "GET /runs?limit=20",
            "GET /runs/{task_id}",
            "GET /runs/{task_id}/summary",
            "GET /runs/{task_id}/snapshot",
            "GET /runs/{task_id}/activity",
            "GET /runs/{task_id}/orchestration",
            "GET /runs/{task_id}/active",
            "GET /runs/{task_id}/steps/{step_id}",
            "GET /runs/{task_id}/steps/{step_id}/artifacts",
            "GET /runs/{task_id}/ledger",
            "GET /runs/{task_id}/package",
            "GET /runs/{task_id}/contract",
            "GET /runs/{task_id}/oversight",
            "GET /runs/{task_id}/dispatch",
            "GET /runs/{task_id}/worker_tasks",
            "GET /runs/{task_id}/worker_tasks?live=1",
            "GET /runs/{task_id}/events",
            "GET /runs/{task_id}/events?limit=20",
            "GET /runs/{task_id}/events?after=0",
            "GET /runs/{task_id}/artifacts",
            "GET /runs/{task_id}/final",
            "GET /runs/{task_id}/final?max_bytes=1000",
            "GET /runs/{task_id}/artifact_text?path=/work/...",
            "GET /runs/{task_id}/artifact_text?path=work/skitarii.patch",
            "GET /runs/{task_id}/artifact_text?path=/work/...&max_bytes=1000",
            "POST /runs/{task_id}/apply_patch",
            "POST /runs/{task_id}/preflight_local",
            "POST /runs/{task_id}/preflight_http",
            "POST /runs/{task_id}/execute_local",
            "POST /runs/{task_id}/execute_http",
            "POST /runs/{task_id}/execute_revision_local",
            "POST /runs/{task_id}/execute_revision_http",
            "POST /runs/{task_id}/resume_local",
            "POST /runs/{task_id}/resume_http",
            "POST /runs/{task_id}/start_local",
            "POST /runs/{task_id}/start_http",
            "POST /runs/{task_id}/start_revision_local",
            "POST /runs/{task_id}/start_revision_http",
            "POST /runs/{task_id}/start_resume_local",
            "POST /runs/{task_id}/start_resume_http",
            "POST /runs/{task_id}/research_loop_local",
            "POST /runs/{task_id}/research_loop_http",
            "POST /runs/{task_id}/start_research_loop_local",
            "POST /runs/{task_id}/start_research_loop_http",
            "POST /recovery/start_resume_local",
            "POST /recovery/start_resume_http",
            "POST /runs/{task_id}/cancel",
            "POST /recover_stale",
        ],
    }
