#!/usr/bin/env python3
from __future__ import annotations

import ast
import hashlib
import json
import re
from pathlib import Path
from typing import Any

from execution_contract import build_blocked_execution_result, build_implemented_execution_result, build_patch_manifest
from execution_preflight import is_repo_relative_path
from greenfield_architect import build_greenfield_project_brief
from greenfield_dependency_worker import run_dependency_worker
from greenfield_memory_worker import build_greenfield_memory_record
from greenfield_review_worker import forbidden_placeholder_markers_found, review_greenfield_project
from greenfield_templates import GREENFIELD_MARKER, PROJECT_TYPES
from greenfield_verification_worker import run_greenfield_verification_loop


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def repo_entries(repo: Path) -> list[Path]:
    if not repo.exists() or not repo.is_dir():
        return []
    return [path for path in repo.iterdir() if path.name not in {".git", "__pycache__"}]


def greenfield_workspace_status(repo: Path) -> dict[str, Any]:
    entries = repo_entries(repo)
    marker = repo / GREENFIELD_MARKER
    owned = marker.exists() and marker.is_file()
    return {
        "kind": "code_brigade_greenfield_workspace_status",
        "repo_path": str(repo),
        "repo_exists": repo.exists(),
        "repo_is_dir": repo.is_dir(),
        "marker": GREENFIELD_MARKER,
        "owned_by_ceraxia": owned,
        "top_level_entry_count": len(entries),
        "top_level_entries": sorted(path.name for path in entries)[:40],
        "greenfield_allowed": repo.exists() and repo.is_dir() and (owned or len(entries) == 0),
    }


def extract_project_spec(task: str) -> dict[str, Any]:
    marker = "CERAXIA_PROJECT:"
    if marker not in task:
        brief = build_greenfield_project_brief(task)
        return {
            "source": "greenfield_project_brief",
            "files": brief["files"],
            "verification_commands": brief["verification_commands"],
            "summary": brief["architecture_plan"]["summary"],
            "greenfield_project_brief": brief,
        }
    raw = task.split(marker, 1)[1].strip()
    payload, _ = json.JSONDecoder().raw_decode(raw)
    if not isinstance(payload, dict):
        raise ValueError("CERAXIA_PROJECT payload must be a JSON object")
    brief = build_greenfield_project_brief(task, payload)
    return {
        "source": "explicit_ceraxia_project",
        "files": brief["files"],
        "verification_commands": brief["verification_commands"],
        "summary": brief["architecture_plan"]["summary"],
        "greenfield_project_brief": brief,
    }


def infer_minimal_project_spec(task: str) -> dict[str, Any]:
    lowered = task.lower()
    project_name = "ceraxia_project"
    name_match = re.search(r"`([^`/\\]+)`", task)
    if name_match:
        project_name = re.sub(r"[^A-Za-z0-9_-]+", "-", name_match.group(1)).strip("-") or project_name
    if any(word in lowered for word in ("api", "http", "fastapi", "server", "сервер", "апи")):
        app_content = (
            "def health():\n"
            "    return {\"ok\": True}\n\n"
            "if __name__ == \"__main__\":\n"
            "    print(health())\n"
        )
        test_content = (
            "import unittest\n"
            "import app\n\n"
            "class AppTests(unittest.TestCase):\n"
            "    def test_health(self):\n"
            "        self.assertEqual(app.health(), {\"ok\": True})\n"
        )
        summary = "minimal Python service scaffold"
    else:
        app_content = (
            "def main():\n"
            "    return \"ready\"\n\n"
            "if __name__ == \"__main__\":\n"
            "    print(main())\n"
        )
        test_content = (
            "import unittest\n"
            "import app\n\n"
            "class AppTests(unittest.TestCase):\n"
            "    def test_main(self):\n"
            "        self.assertEqual(app.main(), \"ready\")\n"
        )
        summary = "minimal Python application scaffold"
    return {
        "source": "inferred_minimal_python_project",
        "summary": summary,
        "files": [
            {"path": GREENFIELD_MARKER, "content": "created-by=ceraxia-code-brigade\n"},
            {"path": "README.md", "content": f"# {project_name}\n\nGenerated by Ceraxia CodeBrigade greenfield project mode.\n"},
            {"path": "app.py", "content": app_content},
            {"path": "test_app.py", "content": test_content},
        ],
        "verification_commands": ["python -m unittest test_app.py", "python -m py_compile app.py"],
    }


def normalize_project_file_rows(files: Any) -> list[dict[str, str]]:
    if not isinstance(files, list):
        raise ValueError("project files must be a list")
    rows: list[dict[str, str]] = []
    for index, item in enumerate(files):
        if not isinstance(item, dict):
            raise ValueError(f"project file {index} must be an object")
        rel_path = str(item.get("path") or "").strip()
        content = item.get("content")
        if not is_repo_relative_path(rel_path):
            raise ValueError(f"project file path must be repo-relative: {rel_path}")
        if Path(rel_path).parts and Path(rel_path).parts[0] in {".git", "__pycache__"}:
            raise ValueError(f"project file path targets forbidden workspace metadata: {rel_path}")
        if not isinstance(content, str):
            raise ValueError(f"project file content must be a string: {rel_path}")
        if rel_path.endswith(".py"):
            ast.parse(content)
        rows.append({"path": rel_path, "content": content})
    if not rows:
        raise ValueError("project file list is empty")
    return rows


def validate_greenfield_project_brief(brief: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    if brief.get("kind") != "code_brigade_greenfield_project_brief":
        problems.append("greenfield_project_brief kind is required")
    if brief.get("contract_version") != "eye-mechanicum.v1":
        problems.append("greenfield_project_brief contract_version is unsupported")
    if brief.get("project_type") not in PROJECT_TYPES:
        problems.append("greenfield_project_brief project_type is unsupported")
    if not isinstance(brief.get("stack"), dict) or not brief.get("stack"):
        problems.append("greenfield_project_brief stack is required")
    if not isinstance(brief.get("entrypoints"), list) or not brief.get("entrypoints"):
        problems.append("greenfield_project_brief entrypoints are required")
    if not isinstance(brief.get("expected_files"), list) or not brief.get("expected_files"):
        problems.append("greenfield_project_brief expected_files are required")
    if not isinstance(brief.get("verification_commands"), list):
        problems.append("greenfield_project_brief verification_commands must be a list")
    if not isinstance(brief.get("run_commands"), list) or not brief.get("run_commands"):
        problems.append("greenfield_project_brief run_commands are required")
    if not isinstance(brief.get("artifact_contract"), dict) or not brief.get("artifact_contract"):
        problems.append("greenfield_project_brief artifact_contract is required")
    if not isinstance(brief.get("workspace_policy"), dict) or brief.get("workspace_policy", {}).get("marker") != GREENFIELD_MARKER:
        problems.append("greenfield_project_brief workspace_policy marker is required")
    if not isinstance(brief.get("definition_of_done"), list) or not brief.get("definition_of_done"):
        problems.append("greenfield_project_brief definition_of_done is required")
    if not isinstance(brief.get("architecture_plan"), dict) or not brief.get("architecture_plan"):
        problems.append("greenfield_project_brief architecture_plan is required")
    if not isinstance(brief.get("file_tree_plan"), list) or not brief.get("file_tree_plan"):
        problems.append("greenfield_project_brief file_tree_plan is required")
    if not isinstance(brief.get("module_contracts"), list) or not brief.get("module_contracts"):
        problems.append("greenfield_project_brief module_contracts are required")
    if not isinstance(brief.get("implementation_plan"), dict) or not brief.get("implementation_plan"):
        problems.append("greenfield_project_brief implementation_plan is required")
    if not isinstance(brief.get("verification_plan"), dict) or not brief.get("verification_plan"):
        problems.append("greenfield_project_brief verification_plan is required")
    return problems


def execute_greenfield_project_brief(brief: dict[str, Any]) -> dict[str, Any]:
    repo = Path(str(brief.get("repo_path") or ""))
    workspace = greenfield_workspace_status(repo)
    if not workspace["repo_exists"] or not workspace["repo_is_dir"]:
        return build_blocked_execution_result(["greenfield repo_path must be an existing directory"], workspace)
    if not workspace["greenfield_allowed"]:
        return build_blocked_execution_result(
            ["greenfield project creation requires an empty directory or .ceraxia_greenfield_workspace marker"],
            workspace,
        )
    try:
        spec = extract_project_spec(str(brief.get("task") or ""))
        project_brief = spec.get("greenfield_project_brief") if isinstance(spec.get("greenfield_project_brief"), dict) else {}
        contract_problems = validate_greenfield_project_brief(project_brief)
        if contract_problems:
            return build_blocked_execution_result(contract_problems, workspace)
        files = list(spec.get("files") if isinstance(spec.get("files"), list) else [])
        if project_brief and not any(isinstance(item, dict) and item.get("path") == "greenfield_project_brief.json" for item in files):
            files.append({"path": "greenfield_project_brief.json", "content": json.dumps(project_brief, ensure_ascii=False, indent=2, sort_keys=True) + "\n"})
        rows = normalize_project_file_rows(files)
    except (ValueError, SyntaxError, json.JSONDecodeError) as exc:
        return build_blocked_execution_result([str(exc)], workspace)
    operation_results: list[dict[str, Any]] = []
    changed_files: list[str] = []
    originals: dict[Path, str | None] = {}
    try:
        for index, row in enumerate(rows):
            rel_path = row["path"]
            path = repo / rel_path
            before_hash = file_sha256(path) if path.exists() and path.is_file() and not path.is_symlink() else ""
            if path.exists() and not path.is_file():
                raise ValueError(f"project file target exists and is not a file: {rel_path}")
            if path.exists() and not workspace["owned_by_ceraxia"] and rel_path != GREENFIELD_MARKER:
                raise ValueError(f"project file target already exists in unowned greenfield workspace: {rel_path}")
            path.parent.mkdir(parents=True, exist_ok=True)
            originals[path] = path.read_text(encoding="utf-8") if path.exists() else None
            path.write_text(row["content"], encoding="utf-8")
            after_hash = file_sha256(path)
            changed_files.append(rel_path)
            operation_results.append(
                {
                    "index": index,
                    "operation": "greenfield_create_or_update_file",
                    "path": rel_path,
                    "status": "applied",
                    "before_sha256": before_hash,
                    "after_sha256": after_hash,
                }
            )
    except Exception as exc:
        for path, original in originals.items():
            if original is None:
                path.unlink(missing_ok=True)
            else:
                path.write_text(original, encoding="utf-8")
        return build_blocked_execution_result(
            [str(exc)],
            workspace,
            f"rolled back {len(originals)} greenfield files",
            operation_results,
            build_patch_manifest([], operation_results, f"rolled back {len(originals)} greenfield files"),
        )
    dependency_report = run_dependency_worker(repo, project_brief)
    commands = spec.get("verification_commands") if isinstance(spec.get("verification_commands"), list) else []
    verification_loop = run_greenfield_verification_loop(repo, [str(command) for command in commands if isinstance(command, str)], project_brief)
    verification = verification_loop.get("final_verification", {}) if isinstance(verification_loop.get("final_verification"), dict) else {}
    greenfield_review = review_greenfield_project(repo, project_brief, dependency_report, verification)
    greenfield_memory_record = build_greenfield_memory_record(project_brief, dependency_report, verification_loop, greenfield_review)
    result = build_implemented_execution_result(
        changed_files,
        f"created {len(changed_files)} greenfield project files from {spec.get('source')}",
        workspace,
        operation_results,
        build_patch_manifest(changed_files, operation_results, ""),
    )
    result["greenfield_project"] = {
        "kind": "code_brigade_greenfield_project_result",
        "spec_source": spec.get("source", ""),
        "summary": spec.get("summary", ""),
        "workspace": workspace,
        "greenfield_project_brief": project_brief,
        "architecture_plan": project_brief.get("architecture_plan", {}) if isinstance(project_brief, dict) else {},
        "file_tree_plan": project_brief.get("file_tree_plan", []) if isinstance(project_brief, dict) else [],
        "module_contracts": project_brief.get("module_contracts", []) if isinstance(project_brief, dict) else [],
        "implementation_plan": project_brief.get("implementation_plan", {}) if isinstance(project_brief, dict) else {},
        "dependency_plan": project_brief.get("dependency_plan", {}) if isinstance(project_brief, dict) else {},
        "verification_plan": project_brief.get("verification_plan", {}) if isinstance(project_brief, dict) else {},
        "dependency_report": dependency_report,
        "verification_loop": verification_loop,
        "greenfield_review": greenfield_review,
        "greenfield_memory_record": greenfield_memory_record,
        "verification": verification,
    }
    result["verification_commands_executed"] = [
        str(item.get("command") or "")
        for item in verification.get("results", [])
        if isinstance(item, dict) and item.get("status") in {"passed", "failed", "blocked", "skipped"}
    ]
    if dependency_report.get("status") == "blocked":
        result["status"] = "blocked"
        result["blockers"] = ["greenfield dependency worker blocked"]
    elif greenfield_review.get("status") == "blocked":
        result["status"] = "blocked"
        result["blockers"] = ["greenfield review blocked"]
    elif verification.get("status") not in {"passed", "planned"}:
        result["status"] = "blocked"
        result["blockers"] = ["greenfield project verification failed"]
    return result
